In [1]:
import pandas as pd 


In [2]:
data = pd.read_csv("CAR DETAILS.csv")
data
data=data[['Model','year','Fuel','Gear','Km_Driven','Price']]
data=data.dropna()

data

Model  year    Fuel    Gear  Km_Driven  \
0                           Maruti 800 AC  2007  Petrol  Manual      70000   
1                Maruti Wagon R LXI Minor  2007  Petrol  Manual      50000   
2                    Hyundai Verna 1.6 SX  2012  Diesel  Manual     100000   
3                  Datsun RediGO T Option  2017  Petrol  Manual      46000   
4                   Honda Amaze VX i-DTEC  2014  Diesel  Manual     141000   
...                                   ...   ...     ...     ...        ...   
4335  Hyundai i20 Magna 1.4 CRDi (Diesel)  2014  Diesel  Manual      80000   
4336           Hyundai i20 Magna 1.4 CRDi  2014  Diesel  Manual      80000   
4337                  Maruti 800 AC BSIII  2009  Petrol  Manual      83000   
4338     Hyundai Creta 1.6 CRDi SX Option  2016  Diesel  Manual      90000   
4339                     Renault KWID RXT  2016  Petrol  Manual      40000   

       Price  
0      60000  
1     135000  
2     600000  
3     250000  
4     450000  
...      ...  
4335  409999  
4336  409999  
4337  110000  
4338  865000  
4339  225000  

[4340 rows x 6 columns]

In [3]:
data.shape
a=data['year'].unique()
a.sort()
a

array([1992, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004,
       2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015,
       2016, 2017, 2018, 2019, 2020], dtype=int64)

In [4]:

data=pd.DataFrame(data)
data


Model  year    Fuel    Gear  Km_Driven  \
0                           Maruti 800 AC  2007  Petrol  Manual      70000   
1                Maruti Wagon R LXI Minor  2007  Petrol  Manual      50000   
2                    Hyundai Verna 1.6 SX  2012  Diesel  Manual     100000   
3                  Datsun RediGO T Option  2017  Petrol  Manual      46000   
4                   Honda Amaze VX i-DTEC  2014  Diesel  Manual     141000   
...                                   ...   ...     ...     ...        ...   
4335  Hyundai i20 Magna 1.4 CRDi (Diesel)  2014  Diesel  Manual      80000   
4336           Hyundai i20 Magna 1.4 CRDi  2014  Diesel  Manual      80000   
4337                  Maruti 800 AC BSIII  2009  Petrol  Manual      83000   
4338     Hyundai Creta 1.6 CRDi SX Option  2016  Diesel  Manual      90000   
4339                     Renault KWID RXT  2016  Petrol  Manual      40000   

       Price  
0      60000  
1     135000  
2     600000  
3     250000  
4     450000  
...      ...  
4335  409999  
4336  409999  
4337  110000  
4338  865000  
4339  225000  

[4340 rows x 6 columns]

In [5]:
data.isnull().sum()

Model        0
year         0
Fuel         0
Gear         0
Km_Driven    0
Price        0
dtype: int64

In [6]:
data.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   Model      4340 non-null   object
 1   year       4340 non-null   int64 
 2   Fuel       4340 non-null   object
 3   Gear       4340 non-null   object
 4   Km_Driven  4340 non-null   int64 
 5   Price      4340 non-null   int64 
dtypes: int64(3), object(3)
memory usage: 203.6+ KB


In [7]:
#### data['Year']=data['Year'].astype(int)


#data['Km_Driven'] = data['Km_Driven'].str.replace('km', '')
#data['Km_Driven']=data['Km_Driven'].astype(int)
#data['Price']=data['Price']
#data
a=data['Model'].str.split(' ').str.slice(0,1).str.join(' ')
data['Model']=data['Model'].str.split(' ').str.slice(0,3).str.join(' ')
data['Company']=a
data=data[['Company','Model','year','Fuel','Gear','Km_Driven','Price']]
data

Company              Model  year    Fuel    Gear  Km_Driven   Price
0      Maruti      Maruti 800 AC  2007  Petrol  Manual      70000   60000
1      Maruti     Maruti Wagon R  2007  Petrol  Manual      50000  135000
2     Hyundai  Hyundai Verna 1.6  2012  Diesel  Manual     100000  600000
3      Datsun    Datsun RediGO T  2017  Petrol  Manual      46000  250000
4       Honda     Honda Amaze VX  2014  Diesel  Manual     141000  450000
...       ...                ...   ...     ...     ...        ...     ...
4335  Hyundai  Hyundai i20 Magna  2014  Diesel  Manual      80000  409999
4336  Hyundai  Hyundai i20 Magna  2014  Diesel  Manual      80000  409999
4337   Maruti      Maruti 800 AC  2009  Petrol  Manual      83000  110000
4338  Hyundai  Hyundai Creta 1.6  2016  Diesel  Manual      90000  865000
4339  Renault   Renault KWID RXT  2016  Petrol  Manual      40000  225000

[4340 rows x 7 columns]

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   Company    4340 non-null   object
 1   Model      4340 non-null   object
 2   year       4340 non-null   int64 
 3   Fuel       4340 non-null   object
 4   Gear       4340 non-null   object
 5   Km_Driven  4340 non-null   int64 
 6   Price      4340 non-null   int64 
dtypes: int64(3), object(4)
memory usage: 237.5+ KB


In [9]:
data.describe()

year      Km_Driven         Price
count  4340.000000    4340.000000  4.340000e+03
mean   2013.090783   66215.777419  5.041273e+05
std       4.215344   46644.102194  5.785487e+05
min    1992.000000       1.000000  2.000000e+04
25%    2011.000000   35000.000000  2.087498e+05
50%    2014.000000   60000.000000  3.500000e+05
75%    2016.000000   90000.000000  6.000000e+05
max    2020.000000  806599.000000  8.900000e+06

In [10]:
data=data[data['Price']<6e6]
data.describe()


year      Km_Driven         Price
count  4338.000000    4338.000000  4.338000e+03
mean   2013.089212   66241.810512  5.004294e+05
std       4.215666   46639.036337  5.523828e+05
min    1992.000000       1.000000  2.000000e+04
25%    2011.000000   35000.000000  2.062492e+05
50%    2014.000000   60000.000000  3.500000e+05
75%    2016.000000   90000.000000  6.000000e+05
max    2020.000000  806599.000000  5.500000e+06

In [11]:
data.to_csv('clean.csv')
data

Company              Model  year    Fuel    Gear  Km_Driven   Price
0      Maruti      Maruti 800 AC  2007  Petrol  Manual      70000   60000
1      Maruti     Maruti Wagon R  2007  Petrol  Manual      50000  135000
2     Hyundai  Hyundai Verna 1.6  2012  Diesel  Manual     100000  600000
3      Datsun    Datsun RediGO T  2017  Petrol  Manual      46000  250000
4       Honda     Honda Amaze VX  2014  Diesel  Manual     141000  450000
...       ...                ...   ...     ...     ...        ...     ...
4335  Hyundai  Hyundai i20 Magna  2014  Diesel  Manual      80000  409999
4336  Hyundai  Hyundai i20 Magna  2014  Diesel  Manual      80000  409999
4337   Maruti      Maruti 800 AC  2009  Petrol  Manual      83000  110000
4338  Hyundai  Hyundai Creta 1.6  2016  Diesel  Manual      90000  865000
4339  Renault   Renault KWID RXT  2016  Petrol  Manual      40000  225000

[4338 rows x 7 columns]

In [12]:
x = data.drop(columns='Price')
y = data['Price']

In [13]:
x

Company              Model  year    Fuel    Gear  Km_Driven
0      Maruti      Maruti 800 AC  2007  Petrol  Manual      70000
1      Maruti     Maruti Wagon R  2007  Petrol  Manual      50000
2     Hyundai  Hyundai Verna 1.6  2012  Diesel  Manual     100000
3      Datsun    Datsun RediGO T  2017  Petrol  Manual      46000
4       Honda     Honda Amaze VX  2014  Diesel  Manual     141000
...       ...                ...   ...     ...     ...        ...
4335  Hyundai  Hyundai i20 Magna  2014  Diesel  Manual      80000
4336  Hyundai  Hyundai i20 Magna  2014  Diesel  Manual      80000
4337   Maruti      Maruti 800 AC  2009  Petrol  Manual      83000
4338  Hyundai  Hyundai Creta 1.6  2016  Diesel  Manual      90000
4339  Renault   Renault KWID RXT  2016  Petrol  Manual      40000

[4338 rows x 6 columns]

In [14]:
y

0        60000
1       135000
2       600000
3       250000
4       450000
         ...  
4335    409999
4336    409999
4337    110000
4338    865000
4339    225000
Name: Price, Length: 4338, dtype: int64

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [16]:
pip install scikit-learn-pipeline-utils

In [17]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [18]:
A=OneHotEncoder(handle_unknown='ignore',sparse_output=True)
A.fit(x[['Company','Model','Fuel','Gear']])

OneHotEncoder(handle_unknown='ignore')

In [19]:
 A.categories_

[array(['Ambassador', 'Audi', 'BMW', 'Chevrolet', 'Daewoo', 'Datsun',
        'Fiat', 'Force', 'Ford', 'Honda', 'Hyundai', 'Isuzu', 'Jaguar',
        'Jeep', 'Kia', 'Land', 'MG', 'Mahindra', 'Maruti', 'Mercedes-Benz',
        'Mitsubishi', 'Nissan', 'OpelCorsa', 'Renault', 'Skoda', 'Tata',
        'Toyota', 'Volkswagen', 'Volvo'], dtype=object),
 array(['Ambassador CLASSIC 1500', 'Ambassador Classic 2000',
        'Ambassador Grand 1800', 'Audi A4 1.8', 'Audi A4 2.0',
        'Audi A4 3.0', 'Audi A4 30', 'Audi A4 35', 'Audi A4 New',
        'Audi A5 Sportback', 'Audi A6 2.0', 'Audi A6 2.7', 'Audi A6 2.8',
        'Audi A8 4.2', 'Audi A8 L', 'Audi Q3 2.0', 'Audi Q3 35',
        'Audi Q5 2.0', 'Audi Q5 3.0', 'Audi Q7 35', 'BMW 3 Series',
        'BMW 5 Series', 'BMW 7 Series', 'BMW X1 sDrive',
        'BMW X1 sDrive20d', 'BMW X5 xDrive', 'Chevrolet Aveo 1.4',
        'Chevrolet Aveo 1.6', 'Chevrolet Aveo U-VA',
        'Chevrolet Beat Diesel', 'Chevrolet Beat LS', 'Chevrolet Beat LT',
  

In [20]:
column_trans= make_column_transformer((OneHotEncoder(categories=A.categories_),['Company','Model','Fuel','Gear']),remainder='passthrough')
column_trans


ColumnTransformer(remainder='passthrough',
                  transformers=[('onehotencoder',
                                 OneHotEncoder(categories=[array(['Ambassador', 'Audi', 'BMW', 'Chevrolet', 'Daewoo', 'Datsun',
       'Fiat', 'Force', 'Ford', 'Honda', 'Hyundai', 'Isuzu', 'Jaguar',
       'Jeep', 'Kia', 'Land', 'MG', 'Mahindra', 'Maruti', 'Mercedes-Benz',
       'Mitsubishi', 'Nissan', 'OpelCorsa', 'Renault', 'Skoda', 'Tata',
       'Toyota', 'V...
       'Volkswagen Vento Celeste', 'Volkswagen Vento Diesel',
       'Volkswagen Vento IPL', 'Volkswagen Vento Magnific',
       'Volkswagen Vento New', 'Volkswagen Vento Petrol', 'Volvo V40 D3',
       'Volvo XC 90', 'Volvo XC60 D3', 'Volvo XC60 D5'], dtype=object),
                                                           array(['CNG', 'Diesel', 'Electric', 'LPG', 'Petrol'], dtype=object),
                                                           array(['Automatic', 'Manual'], dtype=object)]),
                                 ['Company', 'Model', 'Fuel', 'Gear'])])

In [21]:
LR=LinearRegression()

In [22]:
pipe=make_pipeline(column_trans,LR)
pipe.fit(x_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Ambassador', 'Audi', 'BMW', 'Chevrolet', 'Daewoo', 'Datsun',
       'Fiat', 'Force', 'Ford', 'Honda', 'Hyundai', 'Isuzu', 'Jaguar',
       'Jeep', 'Kia', 'Land', 'MG', 'Mahindra', 'Maruti', 'Mercedes-Benz',
       'Mitsubishi', 'Nissan', 'OpelCorsa'...
       'Volkswagen Vento Celeste', 'Volkswagen Vento Diesel',
       'Volkswagen Vento IPL', 'Volkswagen Vento Magnific',
       'Volkswagen Vento New', 'Volkswagen Vento Petrol', 'Volvo V40 D3',
       'Volvo XC 90', 'Volvo XC60 D3', 'Volvo XC60 D5'], dtype=object),
                                                                            array(['CNG', 'Diesel', 'Electric', 'LPG', 'Petrol'], dtype=object),
                                                                            array(['Automatic', 'Manual'], dtype=object)]),
                                                  ['Company', 'Model', 'Fuel',
                                                   'Gear'])])),
                ('linearregression', LinearRegression())])

In [23]:
y_pred=pipe.predict(x_test)
y_pred

array([-4.66268817e+04,  6.32494074e+05,  8.41293366e+04,  4.15421304e+05,
        4.79651525e+05,  3.24421265e+05,  6.60280015e+05,  7.55357242e+05,
        5.34997416e+05,  5.13865000e+05,  2.33054077e+05, -3.89769224e+03,
        1.73038509e+04,  1.64619508e+06,  4.02250953e+05,  3.78598836e+05,
        5.75203047e+05,  2.12972403e+05,  6.10440149e+05,  6.27586533e+05,
        4.09233324e+05,  6.43247848e+05,  6.47133644e+05,  1.45921993e+06,
        8.99856593e+05,  1.37214885e+06,  9.61606261e+03,  4.21892009e+05,
        2.98295279e+05,  1.43661138e+06,  1.43094038e+06,  2.54202592e+05,
        3.81266505e+05,  5.99457358e+05,  1.65990973e+05,  4.18285182e+05,
        5.64119056e+05,  6.89035164e+03,  5.32696067e+05,  1.98317618e+05,
        8.62240746e+05,  1.36575666e+05,  2.94356351e+05,  1.50215828e+05,
        5.26079263e+05,  2.83281061e+05,  4.92710705e+05,  1.29114528e+05,
        4.33902793e+05,  5.51457909e+05,  6.39028720e+05,  5.30598682e+05,
        8.65080692e+03,  

In [24]:
r2_score(y_test,y_pred)

0.49552837422964746

In [29]:
Sc=[]
for c in range(1000):
    x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=c)
    LR=LinearRegression()
    pipe=make_pipeline(column_trans,LR)
    pipe.fit(x_train,y_train)
    y_pred=pipe.predict(x_test)
    Sc.append(r2_score(y_test,y_pred))
     


In [30]:
import numpy as np
d=np.argmax(Sc)
print(d)  #random_state no
print(Sc[d]) #accuracy of the particular random_state

194
0.7678518220444799


In [31]:
import pickle
pickle.dump(pipe,open('C.pkl','wb'))
pipe.predict(pd.DataFrame([['Maruti','Maruti 800 AC',2020,'Diesel','Manual',83000]],columns=['Company','Model','year','Fuel','Gear','Km_Driven']))

array([746619.63479102])

In [32]:
l=data['Fuel'].unique()
l.sort()
l

array(['CNG', 'Diesel', 'Electric', 'LPG', 'Petrol'], dtype=object)